{"uuid": "1f136e77-fac9-4697-bd6f-c78379bcdb6c", "children": ["bbc573f7-31a0-4319-a0d6-393a8610250e"], "befores": [{"name": "xunit_setup_class_fixture_Test_verify_data", "status": "broken", "statusDetails": {"message": "NameError: name 'verify' is not defined\n", "trace": "  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\MSI-NB\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"d:\\code\\tylerhub\\demo\\registration_process\\register_actions_bin\\test_verify_data_bin.py\", line 52, in setup_class\n    verify.browsertype()\n"}, "start": 1629718305356, "stop": 1629718305356}], "start": 1629718305356, "stop": 1629718305680}